In [40]:
import tensorflow as tf
import pandas as pd

In [41]:
data=pd.read_csv(r'car_data.csv')

In [42]:
data.isnull().any()

car_ID              False
symboling           False
CarName             False
fueltype            False
aspiration          False
doornumber          False
carbody             False
drivewheel          False
enginelocation      False
wheelbase           False
carlength           False
carwidth            False
carheight           False
curbweight          False
enginetype          False
cylindernumber      False
enginesize          False
fuelsystem          False
boreratio           False
stroke              False
compressionratio    False
horsepower          False
peakrpm             False
citympg             False
highwaympg          False
price               False
dtype: bool

In [43]:
len(data['CarName'].unique())

147

In [45]:
data.iloc[3,2]='audi 100ls'

In [46]:
data.interpolate(method ='linear', limit_direction ='forward')

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [47]:
print('dimention:',data.ndim)
print('shape:',data.shape)
print('datatypes:',data.dtypes)

dimention: 2
shape: (205, 26)
datatypes: car_ID                int64
symboling             int64
CarName              object
fueltype             object
aspiration           object
doornumber           object
carbody              object
drivewheel           object
enginelocation       object
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype           object
cylindernumber       object
enginesize            int64
fuelsystem           object
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
dtype: object

In [48]:
data.drop(columns=['car_ID'], inplace= True)

In [49]:
data.columns

Index(['symboling', 'CarName', 'fueltype', 'aspiration', 'doornumber',
       'carbody', 'drivewheel', 'enginelocation', 'wheelbase', 'carlength',
       'carwidth', 'carheight', 'curbweight', 'enginetype', 'cylindernumber',
       'enginesize', 'fuelsystem', 'boreratio', 'stroke', 'compressionratio',
       'horsepower', 'peakrpm', 'citympg', 'highwaympg', 'price'],
      dtype='object')

In [50]:
final_data=pd.get_dummies(data, columns=['CarName', 'fueltype', 'aspiration', 'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'enginetype', 'cylindernumber','fuelsystem'],drop_first=True)

In [51]:
final_data.describe()

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,...,cylindernumber_three,cylindernumber_twelve,cylindernumber_two,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,...,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,...,0.004878,0.004878,0.019512,0.321951,0.014634,0.097561,0.004878,0.458537,0.043902,0.004878
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,...,0.069843,0.069843,0.138655,0.468368,0.120377,0.297446,0.069843,0.499498,0.205380,0.069843
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [52]:
import numpy as np

In [58]:
len(final_data)

205

In [70]:
np.random.seed(1111)
mask=np.random.rand(len(final_data))<0.7
len(mask)
train_total=final_data[mask]
test_total=final_data[~mask]
print(len(train_total))
print(len(test_total))

143
62

In [73]:
train_total.head(144)

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,...,cylindernumber_three,cylindernumber_twelve,cylindernumber_two,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,...,0,0,0,0,0,0,0,1,0,0
2,1,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,...,0,0,0,0,0,0,0,1,0,0
3,2,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,...,0,0,0,0,0,0,0,1,0,0
4,2,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,...,0,0,0,0,0,0,0,1,0,0
5,2,99.8,177.3,66.3,53.1,2507,136,3.19,3.40,8.5,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,109.1,188.8,68.9,55.5,2952,141,3.78,3.15,9.5,...,0,0,0,0,0,0,0,1,0,0
201,-1,109.1,188.8,68.8,55.5,3049,141,3.78,3.15,8.7,...,0,0,0,0,0,0,0,1,0,0
202,-1,109.1,188.8,68.9,55.5,3012,173,3.58,2.87,8.8,...,0,0,0,0,0,0,0,1,0,0
203,-1,109.1,188.8,68.9,55.5,3217,145,3.01,3.40,23.0,...,0,0,0,0,0,1,0,0,0,0
204,-1,109.1,188.8,68.9,55.5,3062,141,3.78,3.15,9.5,...,0,0,0,0,0,0,0,1,0,0

In [75]:
train_label=train_total.loc[:,'price']
test_label=test_total.loc[:,'price']

In [79]:
print(len(train_label))
print(len(test_label))
print(test_label)

143
62
1      16500.000
7      18920.000
9      17859.167
17     36880.000
23      7957.000
         ...
174    10698.000
185     8195.000
190     9980.000
193    12290.000
195    13415.000
Name: price, Length: 62, dtype: float64

In [81]:
test_data=test_total.drop(columns=['price'])
train_data=train_total.drop(columns=['price'])
train_data

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,...,cylindernumber_three,cylindernumber_twelve,cylindernumber_two,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,...,0,0,0,0,0,0,0,1,0,0
2,1,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,...,0,0,0,0,0,0,0,1,0,0
3,2,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,...,0,0,0,0,0,0,0,1,0,0
4,2,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,...,0,0,0,0,0,0,0,1,0,0
5,2,99.8,177.3,66.3,53.1,2507,136,3.19,3.40,8.5,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,109.1,188.8,68.9,55.5,2952,141,3.78,3.15,9.5,...,0,0,0,0,0,0,0,1,0,0
201,-1,109.1,188.8,68.8,55.5,3049,141,3.78,3.15,8.7,...,0,0,0,0,0,0,0,1,0,0
202,-1,109.1,188.8,68.9,55.5,3012,173,3.58,2.87,8.8,...,0,0,0,0,0,0,0,1,0,0
203,-1,109.1,188.8,68.9,55.5,3217,145,3.01,3.40,23.0,...,0,0,0,0,0,1,0,0,0,0
204,-1,109.1,188.8,68.9,55.5,3062,141,3.78,3.15,9.5,...,0,0,0,0,0,0,0,1,0,0

In [84]:
{train_data.columns.get_loc(c):
    c for id, c in enumerate(train_data.columns)}

{0: 'symboling',
 1: 'wheelbase',
 2: 'carlength',
 3: 'carwidth',
 4: 'carheight',
 5: 'curbweight',
 6: 'enginesize',
 7: 'boreratio',
 8: 'stroke',
 9: 'compressionratio',
 10: 'horsepower',
 11: 'peakrpm',
 12: 'citympg',
 13: 'highwaympg',
 14: 'CarName_alfa-romero Quadrifoglio',
 15: 'CarName_alfa-romero giulia',
 16: 'CarName_alfa-romero stelvio',
 17: 'CarName_audi 100ls',
 18: 'CarName_audi 4000',
 19: 'CarName_audi 5000',
 20: 'CarName_audi 5000s (diesel)',
 21: 'CarName_audi fox',
 22: 'CarName_bmw 320i',
 23: 'CarName_bmw x1',
 24: 'CarName_bmw x3',
 25: 'CarName_bmw x4',
 26: 'CarName_bmw x5',
 27: 'CarName_bmw z4',
 28: 'CarName_buick century',
 29: 'CarName_buick century luxus (sw)',
 30: 'CarName_buick century special',
 31: 'CarName_buick electra 225 custom',
 32: 'CarName_buick opel isuzu deluxe',
 33: 'CarName_buick regal sport coupe (turbo)',
 34: 'CarName_buick skyhawk',
 35: 'CarName_buick skylark',
 36: 'CarName_chevrolet impala',
 37: 'CarName_chevrolet monte carlo',
 38: 'CarName_chevrolet vega 2300',
 39: 'CarName_dodge challenger se',
 40: 'CarName_dodge colt (sw)',
 41: 'CarName_dodge colt hardtop',
 42: 'CarName_dodge coronet custom',
 43: 'CarName_dodge coronet custom (sw)',
 44: 'CarName_dodge d200',
 45: 'CarName_dodge dart custom',
 46: 'CarName_dodge monaco (sw)',
 47: 'CarName_dodge rampage',
 48: 'CarName_honda accord',
 49: 'CarName_honda accord cvcc',
 50: 'CarName_honda accord lx',
 51: 'CarName_honda civic',
 52: 'CarName_honda civic (auto)',
 53: 'CarName_honda civic 1300',
 54: 'CarName_honda civic 1500 gl',
 55: 'CarName_honda civic cvcc',
 56: 'CarName_honda prelude',
 57: 'CarName_isuzu D-Max ',
 58: 'CarName_isuzu D-Max V-Cross',
 59: 'CarName_isuzu MU-X',
 60: 'CarName_jaguar xf',
 61: 'CarName_jaguar xj',
 62: 'CarName_jaguar xk',
 63: 'CarName_maxda glc deluxe',
 64: 'CarName_maxda rx3',
 65: 'CarName_mazda 626',
 66: 'CarName_mazda glc',
 67: 'CarName_mazda glc 4',
 68: 'CarName_mazda glc custom',
 69: 'CarName_mazda glc custom l',
 70: 'CarName_mazda glc deluxe',
 71: 'CarName_mazda rx-4',
 72: 'CarName_mazda rx-7 gs',
 73: 'CarName_mazda rx2 coupe',
 74: 'CarName_mercury cougar',
 75: 'CarName_mitsubishi g4',
 76: 'CarName_mitsubishi lancer',
 77: 'CarName_mitsubishi mirage',
 78: 'CarName_mitsubishi mirage g4',
 79: 'CarName_mitsubishi montero',
 80: 'CarName_mitsubishi outlander',
 81: 'CarName_mitsubishi pajero',
 82: 'CarName_nissan clipper',
 83: 'CarName_nissan dayz',
 84: 'CarName_nissan fuga',
 85: 'CarName_nissan gt-r',
 86: 'CarName_nissan juke',
 87: 'CarName_nissan kicks',
 88: 'CarName_nissan latio',
 89: 'CarName_nissan leaf',
 90: 'CarName_nissan note',
 91: 'CarName_nissan nv200',
 92: 'CarName_nissan otti',
 93: 'CarName_nissan rogue',
 94: 'CarName_nissan teana',
 95: 'CarName_nissan titan',
 96: 'CarName_peugeot 304',
 97: 'CarName_peugeot 504',
 98: 'CarName_peugeot 504 (sw)',
 99: 'CarName_peugeot 505s turbo diesel',
 100: 'CarName_peugeot 604sl',
 101: 'CarName_plymouth cricket',
 102: 'CarName_plymouth duster',
 103: 'CarName_plymouth fury gran sedan',
 104: 'CarName_plymouth fury iii',
 105: 'CarName_plymouth satellite custom (sw)',
 106: 'CarName_plymouth valiant',
 107: 'CarName_porcshce panamera',
 108: 'CarName_porsche boxter',
 109: 'CarName_porsche cayenne',
 110: 'CarName_porsche macan',
 111: 'CarName_renault 12tl',
 112: 'CarName_renault 5 gtl',
 113: 'CarName_saab 99e',
 114: 'CarName_saab 99gle',
 115: 'CarName_saab 99le',
 116: 'CarName_subaru',
 117: 'CarName_subaru baja',
 118: 'CarName_subaru brz',
 119: 'CarName_subaru dl',
 120: 'CarName_subaru r1',
 121: 'CarName_subaru r2',
 122: 'CarName_subaru trezia',
 123: 'CarName_subaru tribeca',
 124: 'CarName_toyota carina',
 125: 'CarName_toyota celica gt',
 126: 'CarName_toyota celica gt liftback',
 127: 'CarName_toyota corolla',
 128: 'CarName_toyota corolla 1200',
 129: 'CarName_toyota corolla 1600 (sw)',
 130: 'CarName_toyota corolla liftback',
 131: 'CarName_toyota corolla tercel',
 132: 'CarName_toyota corona',
 133: 'CarName_toyota corona hardtop',
 134: 'CarName_toyota corona liftback',
 135: 'CarName_toyota corona mark ii',
 136: 'CarName_toyota cressida',
 137: 'CarName_toyota mark ii',
 138: 'CarName_toyota starlet',
 139: 'CarName_toyota tercel',
 140: 'CarName_toyouta tercel',
 141: 'CarName_vokswagen rabbit',
 142: 'CarName_volkswagen 1131 deluxe sedan',
 143: 'CarName_volkswagen 411 (sw)',
 144: 'CarName_volkswagen dasher',
 145: 'CarName_volkswagen model 111',
 146: 'CarName_volkswagen rabbit',
 147: 'CarName_volkswagen rabbit custom',
 148: 'CarName_volkswagen super beetle',
 149: 'CarName_volkswagen type 3',
 150: 'CarName_volvo 144ea',
 151: 'CarName_volvo 145e (sw)',
 152: 'CarName_volvo 244dl',
 153: 'CarName_volvo 245',
 154: 'CarName_volvo 246',
 155: 'CarName_volvo 264gl',
 156: 'CarName_volvo diesel',
 157: 'CarName_vw dasher',
 158: 'CarName_vw rabbit',
 159: 'fueltype_gas',
 160: 'aspiration_turbo',
 161: 'doornumber_two',
 162: 'carbody_hardtop',
 163: 'carbody_hatchback',
 164: 'carbody_sedan',
 165: 'carbody_wagon',
 166: 'drivewheel_fwd',
 167: 'drivewheel_rwd',
 168: 'enginelocation_rear',
 169: 'enginetype_dohcv',
 170: 'enginetype_l',
 171: 'enginetype_ohc',
 172: 'enginetype_ohcf',
 173: 'enginetype_ohcv',
 174: 'enginetype_rotor',
 175: 'cylindernumber_five',
 176: 'cylindernumber_four',
 177: 'cylindernumber_six',
 178: 'cylindernumber_three',
 179: 'cylindernumber_twelve',
 180: 'cylindernumber_two',
 181: 'fuelsystem_2bbl',
 182: 'fuelsystem_4bbl',
 183: 'fuelsystem_idi',
 184: 'fuelsystem_mfi',
 185: 'fuelsystem_mpfi',
 186: 'fuelsystem_spdi',
 187: 'fuelsystem_spfi'}

In [98]:
mean=train_data.iloc[:,0:14].mean(0)
train_data.iloc[:,0:14]-=mean
std=train_data.iloc[:,0:14].std(0)
train_data.iloc[:,0:14]/=std
train_data.iloc[:,0:14]-=mean
test_data.iloc[:,0:14]/=std

In [99]:
train_data.head()

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,...,cylindernumber_three,cylindernumber_twelve,cylindernumber_two,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,1.645834,-1.643762,-0.466938,-0.870234,-2.065945,-0.049241,0.077706,0.461056,-1.859396,-0.302061,...,0,0,0,0,0,0,0,1,0,0
2,0.102527,-0.725445,-0.277737,-0.217966,-0.549407,0.477242,0.618555,-2.351335,0.637406,-0.302061,...,0,0,0,0,0,0,0,1,0,0
3,0.874181,0.099483,0.147965,0.108168,0.250989,-0.453197,-0.438559,-0.535741,0.416171,-0.056929,...,0,0,0,0,0,0,0,1,0,0
4,0.874181,0.037225,0.147965,0.201350,0.250989,0.479156,0.225211,-0.535741,0.416171,-0.547193,...,0,0,0,0,0,0,0,1,0,0
5,0.874181,0.099483,0.203148,0.154759,-0.254524,-0.127735,0.225211,-0.535741,0.416171,-0.424627,...,0,0,0,0,0,0,0,1,0,0

In [106]:
mean_label=train_label.mean(0)
train_label-=mean_label
std_label=train_label.std(0)
train_label/=std_label
test_label-=mean_label
test_label/=std_label

In [107]:
test_label

1      0.360649
7      0.665723
9      0.531990
17     2.929829
23    -0.716314
         ...
174   -0.370773
185   -0.686311
190   -0.461287
193   -0.170080
195   -0.028258
Name: price, Length: 62, dtype: float64

In [110]:
train=np.array(train_data.iloc[:]).astype('float32')
test=np.array(test_data.iloc[:]).astype('float32')
train_l=np.array(train_label.astype('float32'))
test_l=np.array(test_label.astype('float32'))

In [112]:
test

array([[ 1.6458341 , -1.643762  , -0.46693814, ...,  1.        ,
         0.        ,  0.        ],
       [ 0.10252737,  1.0333649 ,  1.4171876 , ...,  1.        ,
         0.        ,  0.        ],
       [-0.66912603,  0.05278934,  0.27409875, ...,  1.        ,
         0.        ,  0.        ],
       ...,
       [ 1.6458341 , -0.7254452 , -0.7113226 , ...,  1.        ,
         0.        ,  0.        ],
       [-0.66912603,  0.19287156,  0.66038394, ...,  1.        ,
         0.        ,  0.        ],
       [-1.4407794 ,  0.7998945 ,  1.1097361 , ...,  1.        ,
         0.        ,  0.        ]], dtype=float32)

In [120]:
from tensorflow.keras import models
from tensorflow.keras import layers

In [135]:

    model=models.Sequential()
    model.add(layers.Dense(128,activation='relu',input_shape=(train.shape[1],)))
    model.add(layers.Dense(62,activation='relu'))
    model.add(layers.Dense(32,activation='relu'))
    model.add(layers.Dense(1))
    model.compile(optimizer='rmsprop',loss='mse',metrics=['mae'])

In [138]:
h=model.fit(train,train_l,epochs=10,batch_size=100)

Epoch 1/10
2/2 [==============================] - 0s 7ms/step - loss: 0.0156 - mae: 0.0793
Epoch 2/10
2/2 [==============================] - 0s 13ms/step - loss: 0.0224 - mae: 0.1039
Epoch 3/10
2/2 [==============================] - 0s 9ms/step - loss: 0.0317 - mae: 0.1322
Epoch 4/10
2/2 [==============================] - 0s 7ms/step - loss: 0.0174 - mae: 0.0965
Epoch 5/10
2/2 [==============================] - 0s 15ms/step - loss: 0.0102 - mae: 0.0725
Epoch 6/10
2/2 [==============================] - 0s 13ms/step - loss: 0.0112 - mae: 0.0742
Epoch 7/10
2/2 [==============================] - 0s 9ms/step - loss: 0.0115 - mae: 0.0793
Epoch 8/10
2/2 [==============================] - 0s 10ms/step - loss: 0.0280 - mae: 0.1149
Epoch 9/10
2/2 [==============================] - 0s 21ms/step - loss: 0.0335 - mae: 0.1537
Epoch 10/10
2/2 [==============================] - 0s 8ms/step - loss: 0.0126 - mae: 0.0801

In [143]:
test_l,test_a=model.evaluate(test,test_l)

2/2 [==============================] - 0s 6ms/step - loss: 0.0693 - mae: 0.1760

In [145]:
print(test_l)

0.06932587176561356